### ISSUE TITLE
Could you support escape&unescape method

### ISSUE THREAD

**Issue by ericdum** [Gozala/querystring#16] opened 2016-09-12 03:58 UTC
https://nodejs.org/dist/latest-v4.x/docs/api/querystring.html#querystring_querystring_escape
https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html#querystring_querystring_escape_str

**Comment by medikoo** [comment] 2017-04-11 07:47
Closing as duplicate of #6, will be addressed with #20

**Closed by medikoo** 2017-04-11 07:47 UTC
